# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 17:15
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=19)),
                ('pin', models.IntegerField()),
                ('active', models.BooleanField()),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.SmallIntegerField(choices=[(0, 'Check Balance'), (1, 'Withdrawal'), (2, 'Wrong PIN'), (3, 'Blocking card')])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('withdrawal_amount', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.Card')),
            ],
        ),
    ]
