# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
